apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-component-aqculv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-component-aqculv
    app.kubernetes.io/part-of: build-suite-positive-mc-szcz
  name: go-component-aqculv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-component-aqculv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-component-aqculv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-myae-tenant/build-suite-positive-mc-szcz/go-component-aqculv@sha256:b71e2d6f4f3087d62fe2b768980c46ca2e5600693cf6920e5954a9c70b7048ca
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
